set(EXECUTABLE_NAME flow)

if(NOT DEFINED VERSION_MAJOR OR VERSION_MAJOR STREQUAL "")
    set(VERSION_MAJOR "0")
endif()

if(NOT DEFINED VERSION_MINOR OR VERSION_MINOR STREQUAL "")
    set(VERSION_MINOR "0")
endif()

if(NOT DEFINED VERSION_PATCH OR VERSION_PATCH STREQUAL "")
    set(VERSION_PATCH "0")
endif()


set(CLEAN_APP_VERSION "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")
set(APP_VERSION "V${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")

add_compile_definitions(APP_VERSION="${APP_VERSION}")